### ISSUE TITLE
Add to Sublime Text 3 Package Control

### ISSUE THREAD

**Issue by sascha-wolf** [khrizt/GotoLastEdit#7]
I tested the plugin on Sublime Text 3 and it seems to work fine. Would be awesome if we could install it over package control for Sublime Text 3. :)

**Comment by khrizt** [comment]
https://github.com/wbond/package_control_channel/pull/3062

Hope they approve

**Comment by sascha-wolf** [comment]
Package can now be installed via Package Control. Thanks!
